name = "floa-speaker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "FLOA_KV"
id = "122f95ba367c4397a4521eec3fb07c39"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "FloaMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FloaMCP"]
